### ISSUE TITLE
cpu-friendly: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by mbernwieser** [pangyuteng/virtual-background#7]
Hello, running on the `cpu-friendly` branch I receive this error on startup:

```
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "/src/fake.py", line 113, in <module>
fakecam_1  |     frame = get_frame(cap, background_scaled)
fakecam_1  |   File "/src/fake.py", line 79, in get_frame
fakecam_1  |     frame[:,:,c] = frame[:,:,c]*mask + background_scaled[:,:,c]*inv_mask
fakecam_1  | ValueError: operands could not be broadcast together with shapes (400,640) (360,640) 
```

**Comment by brleandro** [comment]
I have a similar erro when using master branch:

vbkgd_fakecam_1 exited with code 1
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "/src/fake.py", line 113, in <module>
fakecam_1  |     frame = get_frame(cap, background_scaled)
fakecam_1  |   File "/src/fake.py", line 61, in get_frame
fakecam_1  |     shrinked_frame = cv2.resize(frame, (width//2, height//2)) 
fakecam_1  | cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-re6mpwzb/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
fakecam_1  |
